#!/usr/bin/env bash
# Displays DNS subdomain information for a given domain using dig and awk

get_subdomain_info() {
    domain="$1"
    subdomain="$2"
    result=$(dig "$subdomain.$domain" | awk '/^'"$subdomain"'\./ {print $4, $5}')
    record_type=$(echo "$result" | awk '{print $1}')
    destination=$(echo "$result" | awk '{print $2}')
    echo "The subdomain $subdomain is a $record_type record and points to $destination"
}

domain=$1
subdomain=$2

if [ -n "$subdomain" ]; then
    get_subdomain_info "$domain" "$subdomain"
else
    for sub in www lb-01 web-01 web-02; do
        get_subdomain_info "$domain" "$sub"
    done
fi
